import { useState, useContext, useEffect } from 'react';
import Button from '../common/Button';
import { ToastContext } from '../../context/ToastContext';

export default function GeneratedDocumentEditor({ document, onRefine, refining = false }) {
  const [content, setContent] = useState(document?.content || '');
  const [refineInstructions, setRefineInstructions] = useState('');
  const toast = useContext(ToastContext);

  useEffect(() => {
    setContent(document?.content || '');
  }, [document?.id, document?.content]);

  const handleCopy = () => {
    navigator.clipboard.writeText(content).then(() => toast.success('Copied to clipboard!')).catch(() => toast.error('Failed to copy'));
  };

  const handleDownload = () => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement('a');
    a.href = url;
    a.download = `${document?.document_type || 'document'}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const wordCount = content.trim().split(/\s+/).filter(Boolean).length;

  return (
    <div>
      <div className="saa-ai-disclaimer">
        <i className="bi bi-exclamation-triangle-fill"></i>
        <div>
          <strong>⚠️ AI-Generated Content</strong>
          <p style={{ margin: '4px 0 0', fontSize: 'var(--saa-font-size-sm)' }}>
            This is a draft generated by AI. Review carefully, personalize, and verify all claims before submitting. This is a starting point only.
          </p>
        </div>
      </div>

      <div className="d-flex justify-content-between align-items-center mb-2 mt-3">
        <span style={{ fontSize: 'var(--saa-font-size-sm)', color: 'var(--saa-gray-500)' }}>{wordCount} words</span>
        <div className="d-flex gap-2">
          <button className="btn btn-sm btn-saa-outline" onClick={handleCopy}><i className="bi bi-clipboard me-1"></i>Copy</button>
          <button className="btn btn-sm btn-saa-outline" onClick={handleDownload}><i className="bi bi-download me-1"></i>Download</button>
        </div>
      </div>

      <textarea className="form-control mb-3" rows={14} value={content} onChange={e => setContent(e.target.value)} style={{ fontFamily: 'Georgia, serif', lineHeight: 1.8 }} />

      <div className="saa-card">
        <div className="saa-card-body">
          <h6><i className="bi bi-arrow-repeat me-2"></i>Refine Document</h6>
          <textarea className="form-control mb-2" rows={2} placeholder="e.g. Make it more formal, add more about my leadership experience..." value={refineInstructions} onChange={e => setRefineInstructions(e.target.value)} />
          <Button variant="gold" size="sm" loading={refining} onClick={() => onRefine?.(refineInstructions)} disabled={!refineInstructions.trim()}>Refine</Button>
        </div>
      </div>
    </div>
  );
}
